/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AuthorizationsApi,
  CapturesApi,
  RefundsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { PayPalPaymentCustom } from "./client-custom";

export class PayPalPayment extends PayPalPaymentCustom {
  readonly authorizations: AuthorizationsApi;
  readonly captures: CapturesApi;
  readonly refunds: RefundsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.authorizations = new AuthorizationsApi(configuration);
    this.captures = new CapturesApi(configuration);
    this.refunds = new RefundsApi(configuration);
  }

}
