/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LinkDescription } from './link-description';
import { Money } from './money';
import { NetworkTransactionReference } from './network-transaction-reference';
import { SellerProtection } from './seller-protection';

/**
 * 
 * @export
 * @interface AuthorizationAllOf
 */
export interface AuthorizationAllOf {
    /**
     * The PayPal-generated ID for the authorized payment.
     * @type {string}
     * @memberof AuthorizationAllOf
     */
    'id'?: string;
    /**
     * 
     * @type {Money}
     * @memberof AuthorizationAllOf
     */
    'amount'?: Money;
    /**
     * The API caller-provided external invoice number for this order. Appears in both the payer\'s transaction history and the emails that the payer receives.
     * @type {string}
     * @memberof AuthorizationAllOf
     */
    'invoice_id'?: string;
    /**
     * The API caller-provided external ID. Used to reconcile API caller-initiated transactions with PayPal transactions. Appears in transaction and settlement reports.
     * @type {string}
     * @memberof AuthorizationAllOf
     */
    'custom_id'?: string;
    /**
     * 
     * @type {NetworkTransactionReference}
     * @memberof AuthorizationAllOf
     */
    'network_transaction_reference'?: NetworkTransactionReference;
    /**
     * 
     * @type {SellerProtection}
     * @memberof AuthorizationAllOf
     */
    'seller_protection'?: SellerProtection;
    /**
     * The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
     * @type {string}
     * @memberof AuthorizationAllOf
     */
    'expiration_time'?: string;
    /**
     * An array of related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
     * @type {Array<LinkDescription>}
     * @memberof AuthorizationAllOf
     */
    'links'?: Array<LinkDescription>;
}

