/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActivityTimestamps } from './activity-timestamps';
import { AuthorizationAllOf } from './authorization-all-of';
import { AuthorizationStatus } from './authorization-status';
import { AuthorizationStatusDetails } from './authorization-status-details';
import { LinkDescription } from './link-description';
import { Money } from './money';
import { NetworkTransactionReference } from './network-transaction-reference';
import { SellerProtection } from './seller-protection';

/**
 * @type Authorization
 * The authorized payment transaction.
 * @export
 */
export type Authorization = ActivityTimestamps & AuthorizationAllOf & AuthorizationStatus;


