/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthorizationStatusDetails } from './authorization-status-details';

/**
 * The status fields for an authorized payment.
 * @export
 * @interface AuthorizationStatus
 */
export interface AuthorizationStatus {
    /**
     * The status for the authorized payment.
     * @type {string}
     * @memberof AuthorizationStatus
     */
    'status'?: AuthorizationStatusStatusEnum;
    /**
     * 
     * @type {AuthorizationStatusDetails}
     * @memberof AuthorizationStatus
     */
    'status_details'?: AuthorizationStatusDetails;
}

type AuthorizationStatusStatusEnum = 'CREATED' | 'CAPTURED' | 'DENIED' | 'PARTIALLY_CAPTURED' | 'VOIDED' | 'PENDING'


