/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AUTHCURRENCYMISMATCH } from './authcurrencymismatch';
import { AUTHORIZATIONALREADYCAPTURED } from './authorizationalreadycaptured';
import { AUTHORIZATIONVOIDED } from './authorizationvoided';
import { CANNOTBEZEROORNEGATIVE } from './cannotbezeroornegative';
import { DECIMALPRECISION } from './decimalprecision';
import { DECIMALSNOTSUPPORTED } from './decimalsnotsupported';
import { INVALIDCURRENCYCODE } from './invalidcurrencycode';
import { PAYEEACCOUNTLOCKEDORCLOSED } from './payeeaccountlockedorclosed';
import { PAYEEACCOUNTRESTRICTED } from './payeeaccountrestricted';
import { PAYERACCOUNTLOCKEDORCLOSED } from './payeraccountlockedorclosed';
import { PAYERCANNOTPAY } from './payercannotpay';
import { REAUTHORIZATIONNOTSUPPORTED } from './reauthorizationnotsupported';
import { TRANSACTIONREFUSED } from './transactionrefused';

/**
 * @type AuthorizationsReauthorize422DetailsInner
 * @export
 */
export type AuthorizationsReauthorize422DetailsInner = INVALIDCURRENCYCODE | CANNOTBEZEROORNEGATIVE | DECIMALPRECISION | DECIMALSNOTSUPPORTED | TRANSACTIONREFUSED | AUTHORIZATIONVOIDED | PAYERCANNOTPAY | AUTHORIZATIONALREADYCAPTURED | PAYEEACCOUNTLOCKEDORCLOSED | PAYERACCOUNTLOCKEDORCLOSED | PAYEEACCOUNTRESTRICTED | REAUTHORIZATIONNOTSUPPORTED | AUTHCURRENCYMISMATCH;


