/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActivityTimestamps } from './activity-timestamps';
import { CaptureAllOf } from './capture-all-of';
import { CaptureStatus } from './capture-status';
import { CaptureStatusDetails } from './capture-status-details';
import { DisbursementMode } from './disbursement-mode';
import { LinkDescription } from './link-description';
import { Money } from './money';
import { NetworkTransactionReference } from './network-transaction-reference';
import { ProcessorResponse } from './processor-response';
import { SellerProtection } from './seller-protection';
import { SellerReceivableBreakdown } from './seller-receivable-breakdown';

/**
 * @type Capture
 * A captured payment.
 * @export
 */
export type Capture = ActivityTimestamps & CaptureAllOf & CaptureStatus;


