/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaptureStatusDetails } from './capture-status-details';

/**
 * The status of a captured payment.
 * @export
 * @interface CaptureStatus
 */
export interface CaptureStatus {
    /**
     * The status of the captured payment.
     * @type {string}
     * @memberof CaptureStatus
     */
    'status'?: CaptureStatusStatusEnum;
    /**
     * 
     * @type {CaptureStatusDetails}
     * @memberof CaptureStatus
     */
    'status_details'?: CaptureStatusDetails;
}

type CaptureStatusStatusEnum = 'COMPLETED' | 'DECLINED' | 'PARTIALLY_REFUNDED' | 'PENDING' | 'REFUNDED' | 'FAILED'


