/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The details of the captured payment status.
 * @export
 * @interface CaptureStatusDetails
 */
export interface CaptureStatusDetails {
    /**
     * The reason why the captured payment status is `PENDING` or `DENIED`.
     * @type {string}
     * @memberof CaptureStatusDetails
     */
    'reason'?: CaptureStatusDetailsReasonEnum;
}

type CaptureStatusDetailsReasonEnum = 'BUYER_COMPLAINT' | 'CHARGEBACK' | 'ECHECK' | 'INTERNATIONAL_WITHDRAWAL' | 'OTHER' | 'PENDING_REVIEW' | 'RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION' | 'REFUNDED' | 'TRANSACTION_APPROVED_AWAITING_FUNDING' | 'UNILATERAL' | 'VERIFICATION_REQUIRED'


