/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CANNOTBENEGATIVE } from './cannotbenegative';
import { CANNOTBEZEROORNEGATIVE1 } from './cannotbezeroornegative1';
import { CAPTUREFULLYREFUNDED } from './capturefullyrefunded';
import { CURRENCYMISMATCH } from './currencymismatch';
import { DECIMALPRECISION1 } from './decimalprecision1';
import { DECIMALSNOTSUPPORTED1 } from './decimalsnotsupported1';
import { DUPLICATEINVOICEID1 } from './duplicateinvoiceid1';
import { INVALIDCURRENCYCODE1 } from './invalidcurrencycode1';
import { MAXNUMBEROFREFUNDSEXCEEDED } from './maxnumberofrefundsexceeded';
import { PARTIALREFUNDNOTALLOWED } from './partialrefundnotallowed';
import { PAYEEACCOUNTLOCKEDORCLOSED } from './payeeaccountlockedorclosed';
import { PAYEEACCOUNTRESTRICTED } from './payeeaccountrestricted';
import { PAYERACCOUNTLOCKEDORCLOSED } from './payeraccountlockedorclosed';
import { PENDINGCAPTURE } from './pendingcapture';
import { PLATFORMFEEEXCEEDED } from './platformfeeexceeded';
import { PLATFORMFEENOTENABLED } from './platformfeenotenabled';
import { REFUNDAMOUNTEXCEEDED } from './refundamountexceeded';
import { REFUNDAMOUNTTOOLOW } from './refundamounttoolow';
import { REFUNDCAPTURECURRENCYMISMATCH } from './refundcapturecurrencymismatch';
import { REFUNDFAILEDINSUFFICIENTFUNDS } from './refundfailedinsufficientfunds';
import { REFUNDISRESTRICTED } from './refundisrestricted';
import { REFUNDNOTALLOWED } from './refundnotallowed';
import { REFUNDNOTPERMITTEDDUETOCHARGEBACK } from './refundnotpermittedduetochargeback';
import { REFUNDTIMELIMITEXCEEDED } from './refundtimelimitexceeded';
import { TRANSACTIONDISPUTED } from './transactiondisputed';

/**
 * @type CapturesRefund422DetailsInner
 * @export
 */
export type CapturesRefund422DetailsInner = CANNOTBEZEROORNEGATIVE1 | DECIMALPRECISION1 | DECIMALSNOTSUPPORTED1 | INVALIDCURRENCYCODE1 | CURRENCYMISMATCH | CANNOTBENEGATIVE | CAPTUREFULLYREFUNDED | REFUNDCAPTURECURRENCYMISMATCH | REFUNDNOTALLOWED | REFUNDTIMELIMITEXCEEDED | REFUNDAMOUNTEXCEEDED | REFUNDAMOUNTTOOLOW | REFUNDFAILEDINSUFFICIENTFUNDS | PARTIALREFUNDNOTALLOWED | MAXNUMBEROFREFUNDSEXCEEDED | PENDINGCAPTURE | DUPLICATEINVOICEID1 | PAYEEACCOUNTLOCKEDORCLOSED | PAYERACCOUNTLOCKEDORCLOSED | PAYEEACCOUNTRESTRICTED | REFUNDNOTPERMITTEDDUETOCHARGEBACK | TRANSACTIONDISPUTED | PLATFORMFEEEXCEEDED | REFUNDISRESTRICTED | PLATFORMFEENOTENABLED;


