/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';
import { PaymentInstruction } from './payment-instruction';

/**
 * 
 * @export
 * @interface CaptureRequestAllOf
 */
export interface CaptureRequestAllOf {
    /**
     * 
     * @type {Money}
     * @memberof CaptureRequestAllOf
     */
    'amount'?: Money;
    /**
     * The API caller-provided external invoice number for this order. Appears in both the payer\'s transaction history and the emails that the payer receives.
     * @type {string}
     * @memberof CaptureRequestAllOf
     */
    'invoice_id'?: string;
    /**
     * Indicates whether you can make additional captures against the authorized payment. Set to `true` if you do not intend to capture additional payments against the authorization. Set to `false` if you intend to capture additional payments against the authorization.
     * @type {boolean}
     * @memberof CaptureRequestAllOf
     */
    'final_capture'?: boolean;
    /**
     * 
     * @type {PaymentInstruction}
     * @memberof CaptureRequestAllOf
     */
    'payment_instruction'?: PaymentInstruction;
    /**
     * An informational note about this settlement. Appears in both the payer\'s transaction history and the emails that the payer receives.
     * @type {string}
     * @memberof CaptureRequestAllOf
     */
    'note_to_payer'?: string;
    /**
     * The payment descriptor on the payer\'s account statement.
     * @type {string}
     * @memberof CaptureRequestAllOf
     */
    'soft_descriptor'?: string;
}

