/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INVALIDPARAMETERSYNTAX1 } from './invalidparametersyntax1';
import { INVALIDSTRINGLENGTH1 } from './invalidstringlength1';
import { MISSINGREQUIREDPARAMETER1 } from './missingrequiredparameter1';

/**
 * @type CapturesRefund400DetailsInner
 * @export
 */
export type CapturesRefund400DetailsInner = MISSINGREQUIREDPARAMETER1 | INVALIDPARAMETERSYNTAX1 | INVALIDSTRINGLENGTH1;


