/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CapturesRefund400 } from './captures-refund400';
import { CapturesRefund400DetailsInner } from './captures-refund400-details-inner';
import { Error400 } from './error400';
import { ErrorLinkDescription } from './error-link-description';

/**
 * @type CapturesRefundPaymentResponse
 * @export
 */
export type CapturesRefundPaymentResponse = CapturesRefund400 & Error400;


