/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DUPLICATEINVOICEID
 */
export interface DUPLICATEINVOICEID {
    /**
     * 
     * @type {string}
     * @memberof DUPLICATEINVOICEID
     */
    'description'?: DUPLICATEINVOICEIDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof DUPLICATEINVOICEID
     */
    'issue'?: DUPLICATEINVOICEIDIssueEnum;
}

type DUPLICATEINVOICEIDDescriptionEnum = 'Requested invoice_id has been previously captured. Possible duplicate transaction.'
type DUPLICATEINVOICEIDIssueEnum = 'DUPLICATE_INVOICE_ID'


