/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorDetails } from './error-details';
import { ErrorLinkDescription } from './error-link-description';

/**
 * Request is not well-formed, syntactically incorrect, or violates schema.
 * @export
 * @interface Error400
 */
export interface Error400 {
    /**
     * 
     * @type {string}
     * @memberof Error400
     */
    'name'?: Error400NameEnum;
    /**
     * 
     * @type {string}
     * @memberof Error400
     */
    'message'?: Error400MessageEnum;
    /**
     * 
     * @type {Array<ErrorDetails>}
     * @memberof Error400
     */
    'details'?: Array<ErrorDetails>;
    /**
     * The PayPal internal ID. Used for correlation purposes.
     * @type {string}
     * @memberof Error400
     */
    'debug_id'?: string;
    /**
     * An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
     * @type {Array<ErrorLinkDescription>}
     * @memberof Error400
     */
    'links'?: Array<ErrorLinkDescription>;
}

type Error400NameEnum = 'INVALID_REQUEST'
type Error400MessageEnum = 'Request is not well-formed, syntactically incorrect, or violates schema.'


