/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorDetails } from './error-details';
import { ErrorLinkDescription } from './error-link-description';

/**
 * The server has not found anything matching the request URI. This either means that the URI is incorrect or the resource is not available.
 * @export
 * @interface Error404
 */
export interface Error404 {
    /**
     * 
     * @type {string}
     * @memberof Error404
     */
    'name'?: Error404NameEnum;
    /**
     * 
     * @type {string}
     * @memberof Error404
     */
    'message'?: Error404MessageEnum;
    /**
     * 
     * @type {Array<ErrorDetails>}
     * @memberof Error404
     */
    'details'?: Array<ErrorDetails>;
    /**
     * The PayPal internal ID. Used for correlation purposes.
     * @type {string}
     * @memberof Error404
     */
    'debug_id'?: string;
    /**
     * An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
     * @type {Array<ErrorLinkDescription>}
     * @memberof Error404
     */
    'links'?: Array<ErrorLinkDescription>;
}

type Error404NameEnum = 'RESOURCE_NOT_FOUND'
type Error404MessageEnum = 'The specified resource does not exist.'


