/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorLocation } from './error-location';

/**
 * The error details. Required for client-side `4XX` errors.
 * @export
 * @interface ErrorDetails
 */
export interface ErrorDetails {
    /**
     * The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value.
     * @type {string}
     * @memberof ErrorDetails
     */
    'description'?: string;
    /**
     * The field that caused the error. If this field is in the body, set this value to the field\'s JSON pointer value. Required for client-side errors.
     * @type {string}
     * @memberof ErrorDetails
     */
    'field'?: string;
    /**
     * The value of the field that caused the error.
     * @type {string}
     * @memberof ErrorDetails
     */
    'value'?: string;
    /**
     * The location of the field that caused the error. Value is `body`, `path`, or `query`.
     * @type {ErrorLocation}
     * @memberof ErrorDetails
     */
    'location'?: ErrorLocation;
    /**
     * The unique, fine-grained application-level error code.
     * @type {string}
     * @memberof ErrorDetails
     */
    'issue': string;
}

