/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorDetails } from './error-details';
import { ErrorLinkDescription } from './error-link-description';

/**
 * The requested action cannot be performed and may require interaction with APIs or processes outside of the current request. This is distinct from a 500 response in that there are no systemic problems limiting the API from performing the request.
 * @export
 * @interface Error422
 */
export interface Error422 {
    /**
     * 
     * @type {string}
     * @memberof Error422
     */
    'name'?: Error422NameEnum;
    /**
     * 
     * @type {string}
     * @memberof Error422
     */
    'message'?: Error422MessageEnum;
    /**
     * 
     * @type {Array<ErrorDetails>}
     * @memberof Error422
     */
    'details'?: Array<ErrorDetails>;
    /**
     * The PayPal internal ID. Used for correlation purposes.
     * @type {string}
     * @memberof Error422
     */
    'debug_id'?: string;
    /**
     * An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
     * @type {Array<ErrorLinkDescription>}
     * @memberof Error422
     */
    'links'?: Array<ErrorLinkDescription>;
}

type Error422NameEnum = 'UNPROCESSABLE_ENTITY'
type Error422MessageEnum = 'The requested action could not be performed, semantically incorrect, or failed business validation.'


