/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorDetails } from './error-details';
import { ErrorLinkDescription } from './error-link-description';

/**
 * The client is not authorized to access this resource, although it may have valid credentials. 
 * @export
 * @interface Error403
 */
export interface Error403 {
    /**
     * 
     * @type {string}
     * @memberof Error403
     */
    'name'?: Error403NameEnum;
    /**
     * 
     * @type {string}
     * @memberof Error403
     */
    'message'?: Error403MessageEnum;
    /**
     * 
     * @type {Array<ErrorDetails>}
     * @memberof Error403
     */
    'details'?: Array<ErrorDetails>;
    /**
     * The PayPal internal ID. Used for correlation purposes.
     * @type {string}
     * @memberof Error403
     */
    'debug_id'?: string;
    /**
     * An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
     * @type {Array<ErrorLinkDescription>}
     * @memberof Error403
     */
    'links'?: Array<ErrorLinkDescription>;
}

type Error403NameEnum = 'NOT_AUTHORIZED'
type Error403MessageEnum = 'Authorization failed due to insufficient permissions.'


