/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorLinkDescription } from './error-link-description';

/**
 * This is either a system or application error, and generally indicates that although the client appeared to provide a correct request, something unexpected has gone wrong on the server.
 * @export
 * @interface Error500
 */
export interface Error500 {
    /**
     * 
     * @type {string}
     * @memberof Error500
     */
    'name'?: Error500NameEnum;
    /**
     * 
     * @type {string}
     * @memberof Error500
     */
    'message'?: Error500MessageEnum;
    /**
     * The PayPal internal ID. Used for correlation purposes.
     * @type {string}
     * @memberof Error500
     */
    'debug_id'?: string;
    /**
     * An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
     * @type {Array<ErrorLinkDescription>}
     * @memberof Error500
     */
    'links'?: Array<ErrorLinkDescription>;
}

type Error500NameEnum = 'INTERNAL_SERVER_ERROR'
type Error500MessageEnum = 'An internal server error occurred.'


