/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorDetails } from './error-details';
import { ErrorLinkDescription } from './error-link-description';

/**
 * The server does not support the request payload\'s media type.
 * @export
 * @interface Error415
 */
export interface Error415 {
    /**
     * 
     * @type {string}
     * @memberof Error415
     */
    'name'?: Error415NameEnum;
    /**
     * 
     * @type {string}
     * @memberof Error415
     */
    'message'?: Error415MessageEnum;
    /**
     * 
     * @type {Array<ErrorDetails>}
     * @memberof Error415
     */
    'details'?: Array<ErrorDetails>;
    /**
     * The PayPal internal ID. Used for correlation purposes.
     * @type {string}
     * @memberof Error415
     */
    'debug_id'?: string;
    /**
     * An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
     * @type {Array<ErrorLinkDescription>}
     * @memberof Error415
     */
    'links'?: Array<ErrorLinkDescription>;
}

type Error415NameEnum = 'UNSUPPORTED_MEDIA_TYPE'
type Error415MessageEnum = 'The server does not support the request payload\'s media type.'


