/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MAXCAPTUREAMOUNTEXCEEDED
 */
export interface MAXCAPTUREAMOUNTEXCEEDED {
    /**
     * 
     * @type {string}
     * @memberof MAXCAPTUREAMOUNTEXCEEDED
     */
    'description'?: MAXCAPTUREAMOUNTEXCEEDEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof MAXCAPTUREAMOUNTEXCEEDED
     */
    'issue'?: MAXCAPTUREAMOUNTEXCEEDEDIssueEnum;
}

type MAXCAPTUREAMOUNTEXCEEDEDDescriptionEnum = 'Capture amount exceeds allowable limit. Please contact customer service or your account manager to request the change to your overage limit. The default overage limit is 115%, which allows the sum of all captures to be up to 115% of the order amount. The ability to over capture is subjected to regulatory approvals.'
type MAXCAPTUREAMOUNTEXCEEDEDIssueEnum = 'MAX_CAPTURE_AMOUNT_EXCEEDED'


