/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExchangeRate } from './exchange-rate';
import { Money } from './money';

/**
 * The net amount. Returned when the currency of the refund is different from the currency of the PayPal account where the merchant holds their funds.
 * @export
 * @interface NetAmountBreakdownItem
 */
export interface NetAmountBreakdownItem {
    /**
     * 
     * @type {Money}
     * @memberof NetAmountBreakdownItem
     */
    'payable_amount'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof NetAmountBreakdownItem
     */
    'converted_amount'?: Money;
    /**
     * 
     * @type {ExchangeRate}
     * @memberof NetAmountBreakdownItem
     */
    'exchange_rate'?: ExchangeRate;
}

