/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardBrand } from './card-brand';

/**
 * Reference values used by the card network to identify a transaction.
 * @export
 * @interface NetworkTransactionReference
 */
export interface NetworkTransactionReference {
    /**
     * Transaction reference id returned by the scheme. For Visa and Amex, this is the \"Tran id\" field in response. For MasterCard, this is the \"BankNet reference id\" field in response. For Discover, this is the \"NRID\" field in response. The pattern we expect for this field from Visa/Amex/CB/Discover is numeric, Mastercard/BNPP is alphanumeric and Paysecure is alphanumeric with special character -.
     * @type {string}
     * @memberof NetworkTransactionReference
     */
    'id': string;
    /**
     * The date that the transaction was authorized by the scheme. This field may not be returned for all networks. MasterCard refers to this field as \"BankNet reference date.
     * @type {string}
     * @memberof NetworkTransactionReference
     */
    'date'?: string;
    /**
     * The card network or brand. Applies to credit, debit, gift, and payment cards.
     * @type {CardBrand}
     * @memberof NetworkTransactionReference
     */
    'network'?: CardBrand;
    /**
     * Reference ID issued for the card transaction. This ID can be used to track the transaction across processors, card brands and issuing banks.
     * @type {string}
     * @memberof NetworkTransactionReference
     */
    'acquirer_reference_number'?: string;
}

