/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PARTIALREFUNDNOTALLOWED
 */
export interface PARTIALREFUNDNOTALLOWED {
    /**
     * 
     * @type {string}
     * @memberof PARTIALREFUNDNOTALLOWED
     */
    'description'?: PARTIALREFUNDNOTALLOWEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PARTIALREFUNDNOTALLOWED
     */
    'issue'?: PARTIALREFUNDNOTALLOWEDIssueEnum;
}

type PARTIALREFUNDNOTALLOWEDDescriptionEnum = 'You cannot do a refund less than the original capture amount.'
type PARTIALREFUNDNOTALLOWEDIssueEnum = 'PARTIAL_REFUND_NOT_ALLOWED'


