/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PAYEEACCOUNTLOCKEDORCLOSED
 */
export interface PAYEEACCOUNTLOCKEDORCLOSED {
    /**
     * 
     * @type {string}
     * @memberof PAYEEACCOUNTLOCKEDORCLOSED
     */
    'description'?: PAYEEACCOUNTLOCKEDORCLOSEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PAYEEACCOUNTLOCKEDORCLOSED
     */
    'issue'?: PAYEEACCOUNTLOCKEDORCLOSEDIssueEnum;
}

type PAYEEACCOUNTLOCKEDORCLOSEDDescriptionEnum = 'Transaction could not complete because payee account is locked or closed.'
type PAYEEACCOUNTLOCKEDORCLOSEDIssueEnum = 'PAYEE_ACCOUNT_LOCKED_OR_CLOSED'


