/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The details for the merchant who receives the funds and fulfills the order. The merchant is also known as the payee.
 * @export
 * @interface PayeeBase
 */
export interface PayeeBase {
    /**
     * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
     * @type {string}
     * @memberof PayeeBase
     */
    'email_address'?: string;
    /**
     * The account identifier for a PayPal account.
     * @type {string}
     * @memberof PayeeBase
     */
    'merchant_id'?: string;
}

