/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PENDINGCAPTURE
 */
export interface PENDINGCAPTURE {
    /**
     * 
     * @type {string}
     * @memberof PENDINGCAPTURE
     */
    'description'?: PENDINGCAPTUREDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PENDINGCAPTURE
     */
    'issue'?: PENDINGCAPTUREIssueEnum;
}

type PENDINGCAPTUREDescriptionEnum = 'Cannot initiate a refund as the capture is pending. Capture is typically pending when the payer has funded the transaction using e-check/bank funded.'
type PENDINGCAPTUREIssueEnum = 'PENDING_CAPTURE'


