/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';
import { PayeeBase } from './payee-base';

/**
 * The platform or partner fee, commission, or brokerage fee that is associated with the transaction. Not a separate or isolated transaction leg from the external perspective. The platform fee is limited in scope and is always associated with the original payment for the purchase unit.
 * @export
 * @interface PlatformFee
 */
export interface PlatformFee {
    /**
     * 
     * @type {Money}
     * @memberof PlatformFee
     */
    'amount': Money;
    /**
     * 
     * @type {PayeeBase}
     * @memberof PlatformFee
     */
    'payee'?: PayeeBase;
}

