/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PREVIOUSREQUESTINPROGRESS
 */
export interface PREVIOUSREQUESTINPROGRESS {
    /**
     * 
     * @type {string}
     * @memberof PREVIOUSREQUESTINPROGRESS
     */
    'description'?: PREVIOUSREQUESTINPROGRESSDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PREVIOUSREQUESTINPROGRESS
     */
    'issue'?: PREVIOUSREQUESTINPROGRESSIssueEnum;
}

type PREVIOUSREQUESTINPROGRESSDescriptionEnum = 'A previous request on this resource is currently in progress. Please wait for sometime and try again. It is best to space out the initial and the subsequent request(s) to avoid receiving this error.'
type PREVIOUSREQUESTINPROGRESSIssueEnum = 'PREVIOUS_REQUEST_IN_PROGRESS'


