/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface REAUTHORIZATIONNOTSUPPORTED
 */
export interface REAUTHORIZATIONNOTSUPPORTED {
    /**
     * 
     * @type {string}
     * @memberof REAUTHORIZATIONNOTSUPPORTED
     */
    'description'?: REAUTHORIZATIONNOTSUPPORTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof REAUTHORIZATIONNOTSUPPORTED
     */
    'issue'?: REAUTHORIZATIONNOTSUPPORTEDIssueEnum;
}

type REAUTHORIZATIONNOTSUPPORTEDDescriptionEnum = 'A reauthorize cannot be attempted on an authorization_id that is the result of a prior reauthorization or on an authorization made on an Order saved using the `v2/orders/id/save` API.'
type REAUTHORIZATIONNOTSUPPORTEDIssueEnum = 'REAUTHORIZATION_NOT_SUPPORTED'


