/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error404 } from './error404';
import { ErrorLinkDescription } from './error-link-description';
import { Model404 } from './model404';
import { Model404DetailsInner } from './model404-details-inner';

/**
 * @type RefundsDetails404Response
 * @export
 */
export type RefundsDetails404Response = Error404 & Model404;


