/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface REFUNDFAILEDINSUFFICIENTFUNDS
 */
export interface REFUNDFAILEDINSUFFICIENTFUNDS {
    /**
     * 
     * @type {string}
     * @memberof REFUNDFAILEDINSUFFICIENTFUNDS
     */
    'description'?: REFUNDFAILEDINSUFFICIENTFUNDSDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof REFUNDFAILEDINSUFFICIENTFUNDS
     */
    'issue'?: REFUNDFAILEDINSUFFICIENTFUNDSIssueEnum;
}

type REFUNDFAILEDINSUFFICIENTFUNDSDescriptionEnum = 'Capture could not be refunded due to insufficient funds. Please check to see if you have sufficient funds in your PayPal account or if the bank account linked to your PayPal account is verified and has sufficient funds.'
type REFUNDFAILEDINSUFFICIENTFUNDSIssueEnum = 'REFUND_FAILED_INSUFFICIENT_FUNDS'


