/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActivityTimestamps } from './activity-timestamps';
import { LinkDescription } from './link-description';
import { MerchantPayableBreakdown } from './merchant-payable-breakdown';
import { Money } from './money';
import { PayeeBase } from './payee-base';
import { RefundAllOf } from './refund-all-of';
import { RefundStatus } from './refund-status';
import { RefundStatusDetails } from './refund-status-details';

/**
 * @type Refund
 * The refund information.
 * @export
 */
export type Refund = ActivityTimestamps & RefundAllOf & RefundStatus;


