/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LinkDescription } from './link-description';
import { MerchantPayableBreakdown } from './merchant-payable-breakdown';
import { Money } from './money';
import { PayeeBase } from './payee-base';

/**
 * 
 * @export
 * @interface RefundAllOf
 */
export interface RefundAllOf {
    /**
     * The PayPal-generated ID for the refund.
     * @type {string}
     * @memberof RefundAllOf
     */
    'id'?: string;
    /**
     * 
     * @type {Money}
     * @memberof RefundAllOf
     */
    'amount'?: Money;
    /**
     * The API caller-provided external invoice number for this order. Appears in both the payer\'s transaction history and the emails that the payer receives.
     * @type {string}
     * @memberof RefundAllOf
     */
    'invoice_id'?: string;
    /**
     * The API caller-provided external ID. Used to reconcile API caller-initiated transactions with PayPal transactions. Appears in transaction and settlement reports.
     * @type {string}
     * @memberof RefundAllOf
     */
    'custom_id'?: string;
    /**
     * Reference ID issued for the card transaction. This ID can be used to track the transaction across processors, card brands and issuing banks.
     * @type {string}
     * @memberof RefundAllOf
     */
    'acquirer_reference_number'?: string;
    /**
     * The reason for the refund. Appears in both the payer\'s transaction history and the emails that the payer receives.
     * @type {string}
     * @memberof RefundAllOf
     */
    'note_to_payer'?: string;
    /**
     * 
     * @type {MerchantPayableBreakdown}
     * @memberof RefundAllOf
     */
    'seller_payable_breakdown'?: MerchantPayableBreakdown;
    /**
     * 
     * @type {PayeeBase}
     * @memberof RefundAllOf
     */
    'payer'?: PayeeBase;
    /**
     * An array of related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
     * @type {Array<LinkDescription>}
     * @memberof RefundAllOf
     */
    'links'?: Array<LinkDescription>;
}

