/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The details of the refund status.
 * @export
 * @interface RefundStatusDetails
 */
export interface RefundStatusDetails {
    /**
     * The reason why the refund has the `PENDING` or `FAILED` status.
     * @type {string}
     * @memberof RefundStatusDetails
     */
    'reason'?: RefundStatusDetailsReasonEnum;
}

type RefundStatusDetailsReasonEnum = 'ECHECK'


