/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';
import { PaymentInstruction2 } from './payment-instruction2';

/**
 * Refunds a captured payment, by ID. For a full refund, include an empty request body. For a partial refund, include an <code>amount</code> object in the request body.
 * @export
 * @interface RefundRequest
 */
export interface RefundRequest {
    /**
     * 
     * @type {Money}
     * @memberof RefundRequest
     */
    'amount'?: Money;
    /**
     * The API caller-provided external ID. Used to reconcile API caller-initiated transactions with PayPal transactions. Appears in transaction and settlement reports. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof RefundRequest
     */
    'custom_id'?: string;
    /**
     * The API caller-provided external invoice ID for this order. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof RefundRequest
     */
    'invoice_id'?: string;
    /**
     * The reason for the refund. Appears in both the payer\'s transaction history and the emails that the payer receives. The pattern is defined by an external party and supports Unicode.
     * @type {string}
     * @memberof RefundRequest
     */
    'note_to_payer'?: string;
    /**
     * 
     * @type {PaymentInstruction2}
     * @memberof RefundRequest
     */
    'payment_instruction'?: PaymentInstruction2;
}

