/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface REFUNDAMOUNTEXCEEDED
 */
export interface REFUNDAMOUNTEXCEEDED {
    /**
     * 
     * @type {string}
     * @memberof REFUNDAMOUNTEXCEEDED
     */
    'description'?: REFUNDAMOUNTEXCEEDEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof REFUNDAMOUNTEXCEEDED
     */
    'issue'?: REFUNDAMOUNTEXCEEDEDIssueEnum;
}

type REFUNDAMOUNTEXCEEDEDDescriptionEnum = 'The refund amount must be less than or equal to the capture amount that has not yet been refunded.'
type REFUNDAMOUNTEXCEEDEDIssueEnum = 'REFUND_AMOUNT_EXCEEDED'


