/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Identifiers related to a specific resource.
 * @export
 * @interface RelatedIds
 */
export interface RelatedIds {
    /**
     * Order ID related to the resource.
     * @type {string}
     * @memberof RelatedIds
     */
    'order_id'?: string;
    /**
     * Authorization ID related to the resource.
     * @type {string}
     * @memberof RelatedIds
     */
    'authorization_id'?: string;
    /**
     * Capture ID related to the resource.
     * @type {string}
     * @memberof RelatedIds
     */
    'capture_id'?: string;
}

