/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExchangeRate } from './exchange-rate';
import { Money } from './money';
import { PlatformFee } from './platform-fee';

/**
 * The detailed breakdown of the capture activity. This is not available for transactions that are in pending state.
 * @export
 * @interface SellerReceivableBreakdown
 */
export interface SellerReceivableBreakdown {
    /**
     * 
     * @type {Money}
     * @memberof SellerReceivableBreakdown
     */
    'gross_amount': Money;
    /**
     * 
     * @type {Money}
     * @memberof SellerReceivableBreakdown
     */
    'paypal_fee'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof SellerReceivableBreakdown
     */
    'paypal_fee_in_receivable_currency'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof SellerReceivableBreakdown
     */
    'net_amount'?: Money;
    /**
     * 
     * @type {Money}
     * @memberof SellerReceivableBreakdown
     */
    'receivable_amount'?: Money;
    /**
     * 
     * @type {ExchangeRate}
     * @memberof SellerReceivableBreakdown
     */
    'exchange_rate'?: ExchangeRate;
    /**
     * An array of platform or partner fees, commissions, or brokerage fees that associated with the captured payment.
     * @type {Array<PlatformFee>}
     * @memberof SellerReceivableBreakdown
     */
    'platform_fees'?: Array<PlatformFee>;
}

