/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The capture identification-related fields. Includes the invoice ID, custom ID, note to payer, and soft descriptor.
 * @export
 * @interface SupplementaryPurchaseData
 */
export interface SupplementaryPurchaseData {
    /**
     * The API caller-provided external invoice number for this order. Appears in both the payer\'s transaction history and the emails that the payer receives.
     * @type {string}
     * @memberof SupplementaryPurchaseData
     */
    'invoice_id'?: string;
    /**
     * An informational note about this settlement. Appears in both the payer\'s transaction history and the emails that the payer receives.
     * @type {string}
     * @memberof SupplementaryPurchaseData
     */
    'note_to_payer'?: string;
}

