/*
Payments

Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

The version of the OpenAPI document: 2.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TRANSACTIONDISPUTED
 */
export interface TRANSACTIONDISPUTED {
    /**
     * 
     * @type {string}
     * @memberof TRANSACTIONDISPUTED
     */
    'description'?: TRANSACTIONDISPUTEDDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof TRANSACTIONDISPUTED
     */
    'issue'?: TRANSACTIONDISPUTEDIssueEnum;
}

type TRANSACTIONDISPUTEDDescriptionEnum = 'Partial refunds cannot be offered at this time because there is an open case on this transaction. Visit the PayPal Resolution Center to review this case.'
type TRANSACTIONDISPUTEDIssueEnum = 'TRANSACTION_DISPUTED'


